modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/ThePandaParade/CreateAutomative/issues"
license = "GPL-v2.1 License"

[[mods]]
modId = "create_automative"
version = "${version}"
displayName = "Create: Automative"
authors = "Robyn-Dawn 'ThePandaParade' B. <robyn@pandapa.ws>"
description = '''
Automate everything with Create!
'''
logoFile = "assets/icon.png"

[[dependencies.create_automative]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_automative]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_automative]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.create_automative]]
modId = "create"
mandatory = true
versionRange = "[0.4.0,)"
ordering = "AFTER"
side = "BOTH"